name: Authorization

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Realizar o zip do projeto
        id: package
        run: |
          zip -r lambda_function.zip . -x "*.git*"

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: lambda_function
          path: lambda_function.zip  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Realizar download do artefato
        uses: actions/download-artifact@v4
        with:
          name: lambda_function
          path: .  

      - name: Realizar deploy da LAMBDA
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda_function.zip
