name: Authorization

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: ${{ steps.build.outputs.build-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Save node_modules artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules  

      - name: Set build path
        id: build
        run: echo "build-path=${GITHUB_WORKSPACE}" >> $GITHUB_OUTPUT

  package:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      zip-path: ${{ steps.package.outputs.zip-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules  

      - name: Zip project files
        id: package
        run: |
          zip -r lambda_function.zip . -x "*.git*"

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda_function
          path: lambda_function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda_function
          path: .  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda_function.zip
